[[colors.indexed_colors]]
color = "#b6927b"
index = 16

[[colors.indexed_colors]]
color = "#b98d7b"
index = 17

[colors.normal]
black = "#0d0c0c"
blue = "#8ba4b0"
cyan = "#8ea4a2"
green = "#8a9a7b"
magenta = "#a292a3"
red = "#c4746e"
white = "#C8C093"
yellow = "#c4b28a"

[colors.primary]
background = "#181616"
foreground = "#c5c9c5"

[colors.selection]
background = "#2D4F67"
foreground = "#C8C093"
